apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-06T21:29:54Z"
  labels:
    app: hw
  name: hw
  namespace: default
  resourceVersion: "15065"
  selfLink: /api/v1/namespaces/default/services/hw
  uid: ba1d0ab9-8fe0-11ea-82dd-42010a8001a2
spec:
  clusterIP: 10.0.9.127
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31139
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hw
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.188.155.82
